name: Generate 3D Contribution Chart

on:
  schedule:
    - cron: "0 0 * * *"   # Runs daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write  # REQUIRED to push to output branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate 3D Chart
        uses: yoshi389111/github-profile-3d-contrib@0.10.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          username: VISHWA-SANTHI
          theme: "profile-night-green"

      - name: Push to output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: profile-3d-contrib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
